<a href="https://colab.research.google.com/github/KwangmyungLee/Algorithm-Practice-/blob/main/NumPy_%ED%95%9C%EB%B2%88%EC%97%90_%EC%A0%9C%EB%8C%80%EB%A1%9C_%EB%B0%B0%EC%9A%B0%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy 한번에 제대로 배우기



---



## NumPy 특징

* Numerical Python의 약자
* 고성능 과학 계산용 패키지로 강력한 N차원 배열 객체
* 범용적 데이터 처리에 사용 가능한 다차원 컨테이너
* 정교한 브로드캐스팅(broadcasting) 기능
* 파이썬의 자료형 list와 비슷하지만, 더 빠르고 메모리를 효율적으로 관리
* 반복문 없이 데이터 배열에 대한 처리를 지원하여 빠르고 편리
* 데이터 과학 도구에 대한 생태계의 핵심을 이루고 있음

In [2]:
 import numpy as np
 np.__version__

'1.19.5'



---



## 배열 생성

### 리스트로 배열 만들기


In [8]:
a1 = np.array([1,2,3,4,5])
print(a1)
print(type(a1))
print(a1.shape)
print(a1[0], a1[1], a1[3])
a1[0] = 4
a1[1] = 5
print(a1)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1 2 4
[4 5 3 4 5]


In [10]:
a2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(a2)
print(a2.shape)
print(a2[0,0], a2[1,1], a2[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
1 5 9


In [11]:
a3 = np.array([[[1,2,3], [4,5,6,], [7,8,9]],
               [[1,2,3], [4,5,6,], [7,8,9]],
               [[1,2,3], [4,5,6,], [7,8,9]]])
print(a3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


### 배열 생성 및 초기화

* `zeros()`: 모든 요소를 0으로 초기화

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

* `ones()`: 모든 요소를 1로 초기화

In [16]:
np.ones(10)
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

* `full()`: 모든 요소를 지정한 값으로 초기화

In [17]:
np.full((3,3), 1.23)

array([[1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23]])

* `eye()`: 단위행렬(identity matrix) 생성
  + 주대각선의 원소가 모두 1이고 나머지 원소는 모두 0인 정사각 행렬

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

* `tri()`: 삼각행렬 생성

In [19]:
np.tri(3)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

* `empty()`: 초기화되지 않은 배열 생성
  + 초기화가 없어서 배열 생성비용 저렴하고 빠름
  + 초기화되지 않아서 기존 메모리 위치에 존재하는 값이 있음

In [20]:
np.empty(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

* `_like()`: 지정된 배열과 shape가 같은 행렬 생성
  + `np.zeros_like()`
  + `np.ones_like()`
  + `np.full_like()`
  + `np.empty_like()`

In [22]:
print(a1)
np.zeros_like(a1)

[4 5 3 4 5]


array([0, 0, 0, 0, 0])

In [23]:
print(a2)
np.ones_like(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [24]:
print(a3)
np.full_like(a3, 10)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


array([[[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]])

### 생성한 값으로 배열 생성

* `arange()`: 정수 범위로 배열 생성

In [25]:
np.arange(0,30,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

* `linspace()`: 범위 내에서 균등 간격의 배열 생성

In [26]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

* `logspace()`: 범위 내에서 균등간격으로 로그 스케일로 배열 생성

In [28]:
np.logspace(0.1, 1, 20)

array([ 1.25892541,  1.40400425,  1.565802  ,  1.74624535,  1.94748304,
        2.1719114 ,  2.42220294,  2.70133812,  3.0126409 ,  3.35981829,
        3.74700446,  4.17881006,  4.66037703,  5.19743987,  5.79639395,
        6.46437163,  7.2093272 ,  8.04013161,  8.9666781 , 10.        ])

### 랜덤값으로 배열 생성


* `random.random()`: 랜덤한 수의 배열 생성

In [29]:
np.random.random((3,3))

array([[0.2055313 , 0.03053284, 0.89227604],
       [0.42675898, 0.46113144, 0.42015785],
       [0.0485085 , 0.32329421, 0.74000029]])

* `random.randint()`: 일정 구간의 랜덤 정수의 배열 생성

In [32]:
np.random.randint(0, 10, (3,3))

array([[5, 3, 5],
       [7, 0, 9],
       [2, 8, 8]])

* `random.normal()`: 정규분포(normal distribution)를 고려한 랜덤한 수의 배열 생성
* 평균=0, 표준편차=1, 3 x 3 배열

In [33]:
np.random.normal(0,1,(3,3))

array([[ 2.09753491, -0.25954608, -0.60459788],
       [ 0.36267596, -0.61894142,  0.15728288],
       [-0.56380003, -1.66411967, -1.07750717]])

* `random.rand()`: 균등분포(uniform distribution)를 고려한 랜덤한 수의 배열 생성

In [34]:
np.random.rand(3,3)

array([[0.87492749, 0.32487355, 0.70600848],
       [0.80523099, 0.35927916, 0.97177835],
       [0.83246374, 0.1871033 , 0.49015844]])

* `random.randn()`: 표준 정규 분포(standard normal distribution)를 고려한 랜덤한 수의 배열 생성

In [35]:
np.random.randn(3,3)

array([[ 0.91383054, -0.05038927, -0.44052663],
       [-0.41114785,  0.79956195,  0.85877268],
       [-0.97007889,  0.73019985,  0.8023132 ]])

### 표준 데이터 타입

In [36]:
np.zeros(20, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [37]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [38]:
np.full((3,3), 1.0, dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 날짜/시간 배열 생성


In [39]:
date = np.array('2020-01-01', dtype=np.datetime64)
date

array('2020-01-01', dtype='datetime64[D]')

In [40]:
date + np.arange(12)

array(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
       '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
       '2020-01-09', '2020-01-10', '2020-01-11', '2020-01-12'],
      dtype='datetime64[D]')

In [41]:
datetime = np.datetime64('2020-06-01 12:00')
datetime

numpy.datetime64('2020-06-01T12:00')

In [43]:
datetime = np.datetime64('2020-06-01 12:00:12.34', 'ns')
datetime

numpy.datetime64('2020-06-01T12:00:12.340000000')



---



## 배열 조회

### 배열 속성 정보

In [46]:
def array_info(array):
  print(array)
  print("ndim:", array.ndim)
  print("shape:", array.shape)
  print("type:", array.dtype)
  print("size:", array.size)
  print("itemsize:", array.itemsize)
  print("nbytes:", array.nbytes)
  print("strides:", array.strides)

In [47]:
array_info(a1)

[4 5 3 4 5]
ndim: 1
shape: (5,)
type: int64
size: 5
itemsize: 8
nbytes: 40
strides: (8,)


In [48]:
array_info(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
ndim: 2
shape: (3, 3)
type: int64
size: 9
itemsize: 8
nbytes: 72
strides: (24, 8)


In [49]:
array_info(a3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
ndim: 3
shape: (3, 3, 3)
type: int64
size: 27
itemsize: 8
nbytes: 216
strides: (72, 24, 8)


### 인덱싱(Indexing)

In [50]:
print(a1)
print(a1[0])
print(a1[2])
print(a1[-1])
print(a1[-2])

[4 5 3 4 5]
4
3
5
4


In [51]:
print(a2)
print(a2[0,0])
print(a2[0,2])
print(a2[1,1])
print(a2[2,-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
3
5
9


In [52]:
print(a3)
print(a3[0,0,0])
print(a3[1,1,1])
print(a3[2,2,2])
print(a3[2,-1,-1])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
1
5
9
9


### 슬라이싱(Slicing)

* 슬라이싱 구문: `a[start:stop:step]`
* 기본값: start=0, stop=ndim, step=1

In [53]:
print(a1)
print(a1[0:2])
print(a1[0:])
print(a1[:1])
print(a1[::2])
print(a1[::-1])

[4 5 3 4 5]
[4 5]
[4 5 3 4 5]
[4]
[4 3 5]
[5 4 3 5 4]


In [55]:
print(a2)
print(a2[1])
print(a2[1, :])
print(a2[:2, :2])
print(a2[1:, ::-1])
print(a2[::-1, ::-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
[4 5 6]
[[1 2]
 [4 5]]
[[6 5 4]
 [9 8 7]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


### 불리언 인덱싱(Boolean Indexing)

* 배열 각 요소의 선택 여부를 불리언(True or False)로 지정
* True 값인 인덱스의 값만 조회

In [59]:
print(a1)
bi = [False, True, True, False, True]
print(a1[bi])
bi = [True, False, True, True, False]
print(a1[bi])

[4 5 3 4 5]
[5 3 5]
[4 3 4]


In [60]:
print(a2)
bi = np.random.randint(0, 2, (3,3), dtype=bool)
print(bi)
print(a2[bi])  

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ True  True  True]
 [ True  True False]
 [False False False]]
[1 2 3 4 5]


### 팬시 인덱싱(Fancy Indedxing)

In [62]:
print(a1)
print([a1[0], a1[2]])
ind = [0,2]
print(a1[ind])
ind = np.array([[0,1],
                [2,0]])
print(a1[ind])

[4 5 3 4 5]
[4, 3]
[4 3]
[[4 5]
 [3 4]]


In [67]:
print(a2)
row = np.array([0,2])
col = np.array([1,2])
print(row)
print(col)
print(a2[row,col])
print(a2[row, :])
print(a2[:, col])
print(a2[2, col])
print(a2[row, 1:])
print(a2[1:, col])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[0 2]
[1 2]
[2 9]
[[1 2 3]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]
[8 9]
[[2 3]
 [8 9]]
[[5 6]
 [8 9]]




---



## 배열 값 삽입/수정/삭제/복사

### 배열 값 삽입

* `insert()`: 배열의 특정 위치에 값 삽입
* axis를 지정하지 않으면 1차원 배열로 변환
* 추가할 방향을 axis로 지정
* 원본 배열 변경없이 새로운 배열 반환

In [71]:
print(a1)
b1 = np.insert(a1, 0, 10)
print(b1)
c1 = np.insert(a1, 2, 10)
print(c1)

[4 5 3 4 5]
[10  4  5  3  4  5]
[ 4  5 10  3  4  5]


In [73]:
print(a2)
b2 = np.insert(a2, 1, 10, axis=0) # axis=0 은 가로 1 은 세로
print(b2)
c2 = np.insert(a2, 1, 10, axis=1)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [10 10 10]
 [ 4  5  6]
 [ 7  8  9]]
[[ 1 10  2  3]
 [ 4 10  5  6]
 [ 7 10  8  9]]


### 배열 값 수정

* 배열의 인덱싱으로 접근하여 값 수정

In [77]:
print(a1)
a1[0] = 1
a1[1] = 2
a1[2] = 3
print(a1)
a1[:1] = 9
print(a1)
i = np.array([1,3,4])
a1[i] = 0
print(a1)
a1[i] += 4
print(a1)

[9 0 3 0 0]
[1 2 3 0 0]
[9 2 3 0 0]
[9 0 3 0 0]
[9 4 3 4 4]


In [81]:
print(a2)
a2[0, 0] = 1
a2[1, 1] = 2
a2[2, 2] = 3
a2[0] = 1
print(a2)
a2[1:,2] = 9
print(a2)
row = np.array([0,1])
col = np.array([1,2])
a2[row, col] = 0
print(a2)

[[1 0 1]
 [4 2 0]
 [7 8 9]]
[[1 1 1]
 [4 2 0]
 [7 8 3]]
[[1 1 1]
 [4 2 9]
 [7 8 9]]
[[1 0 1]
 [4 2 0]
 [7 8 9]]


### 배열 값 삭제

* `delete()`: 배열의 특정 위치에 값 삭제
* axis를 지정하지 않으면 1차원 배열로 변환
* 삭제할 방향을 axis로 지정
* 원본 배열 변경없이 새로운 배열 반환

In [83]:
print(a1)
b1 = np.delete(a1, 1)
print(b1)
print(a1)

[9 4 3 4 4]
[9 3 4 4]
[9 4 3 4 4]


In [84]:
print(a2)
b2 = np.delete(a2, 1, axis=0)
print(b2)
c2 = np.delete(a2, 1, axis=1)
print(c2)

[[1 0 1]
 [4 2 0]
 [7 8 9]]
[[1 0 1]
 [7 8 9]]


### 배열 복사

* 리스트 자료형과 달리 배열의 슬라이스는 복사본이 아님

In [87]:
print(a2) # 슬라이싱은 원본 데이터를 바꿈
print(a2[:2,:2])
a2_sub = a2[:2, :2]
print(a2_sub)
a2_sub[:, 1]=0
print(a2_sub)
print(a2) 

[[1 0 1]
 [4 2 0]
 [7 8 9]]
[[1 0]
 [4 2]]
[[1 0]
 [4 2]]
[[1 0]
 [4 0]]
[[1 0 1]
 [4 0 0]
 [7 8 9]]



* `copy()`: 배열이나 하위 배열 내의 값을 명시적으로 복사

In [89]:
print(a2)
a2_sub_copy = a2[:2,:2].copy()
print(a2_sub_copy)
a2_sub_copy[:,1] = 1
print(a2_sub_copy)
print(a2)

[[1 0 1]
 [4 0 0]
 [7 8 9]]
[[1 0]
 [4 0]]
[[1 1]
 [4 1]]
[[1 0 1]
 [4 0 0]
 [7 8 9]]




---



## 배열 변환

### 배열 전치 및 축 변경

In [90]:
print(a2)
print(a2.T)

[[1 0 1]
 [4 0 0]
 [7 8 9]]
[[1 4 7]
 [0 0 8]
 [1 0 9]]


In [91]:
print(a3)
print(a3.T)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 1 1]
  [4 4 4]
  [7 7 7]]

 [[2 2 2]
  [5 5 5]
  [8 8 8]]

 [[3 3 3]
  [6 6 6]
  [9 9 9]]]


In [92]:
print(a2)
print(a2.swapaxes(1,0))

[[1 0 1]
 [4 0 0]
 [7 8 9]]
[[1 4 7]
 [0 0 8]
 [1 0 9]]


In [93]:
print(a3)
print(a3.swapaxes(0,1))
print(a3.swapaxes(1,2))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]
  [4 5 6]]

 [[7 8 9]
  [7 8 9]
  [7 8 9]]]
[[[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]]


### 배열 재구조화


* `reshape()`: 배열의 형상을 변경

In [95]:
n1 = np.arange(1, 10)
print(n1)
print(n1.reshape(3,3))

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


* `newaxis()`: 새로운 축 추가

In [96]:
print(n1)
print(n1[np.newaxis, :5])
print(n1[:5, np.newaxis])

[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


### 배열 크기 변경

* 배열 모양만 변경

In [99]:
n2 = np.random.randint(0,10,(2,5))
print(n2)
n2.resize((5,2))
print(n2)

[[3 0 4 7 7]
 [3 2 7 7 1]]
[[3 0]
 [4 7]
 [7 3]
 [2 7]
 [7 1]]


* 배열 크기 증가
* 남은 공간은 0으로 채워짐

In [100]:
n2.resize((5,5))
print(n2)

[[3 0 4 7 7]
 [3 2 7 7 1]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


* 배열 크기 감소
* 포함되지 않은 값은 삭제됨

In [101]:
n2.resize((3,3))
print(n2)

[[3 0 4]
 [7 7 3]
 [2 7 7]]


### 배열 추가

* `append()`: 배열의 끝에 값 추가

In [102]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2 = np.arange(10,19).reshape(3,3)
print(b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


* axis 지정이 없으면 1차원 배열 형태로 변형되어 결합

In [103]:
c2 = np.append(a2, b2)
print(c2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


* axis를 0으로 지정
* shape[0]을 제외한 나머지 shape은 같아야 함

In [104]:
c2 = np.append(a2, b2, axis=0)
print(c2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


* axis를 1로 지정
* shape[1]을 제외한 나머지 shape은 같아야 함

In [105]:
c2 = np.append(a2, b2, axis=1)
print(c2)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


### 배열 연결

* `concatenate()`: 튜플이나 배열의 리스트를 인수로 사용해 배열 연결

In [106]:
a1 = np.array([1,3,5])
b1 = np.array([2,4,6])
np.concatenate([a1, b1])

array([1, 3, 5, 2, 4, 6])

In [107]:
c1 = np.array([7,8,9])
np.concatenate([a1, b1, c1])

array([1, 3, 5, 2, 4, 6, 7, 8, 9])

In [109]:
 a2 = np.array([[1,2,3], 
                [4,5,6]])
 np.concatenate([a2,a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [110]:
 a2 = np.array([[1,2,3], 
                [4,5,6]])
 np.concatenate([a2,a2], axis= 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

* `vstack()`: 수직 스택(vertical stack), 1차원으로 연결

In [111]:
np.vstack([a2, a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

* `hstack()`: 수평 스택(horizontal stack), 2차원으로 연결

In [112]:
np.hstack([a2, a2])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

* `dstack()`: 깊이 스택(depth stack), 3차원으로 연결

In [113]:
np.dstack([a2, a2])

array([[[1, 1],
        [2, 2],
        [3, 3]],

       [[4, 4],
        [5, 5],
        [6, 6]]])

* `stack()`: 새로운 차원으로 연결

In [114]:
np.stack([a2, a2])

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

### 배열 분할

* `split()`: 배열 분할

In [117]:
a1 = np.arange(0, 10)
print(a1)
b1, c1 = np.split(a1, [5])
print(b1, c1)
b1, c1, d1, e1, f1 = np.split(a1, [2,4,6,8])
print(b1, c1, d1, e1, f1)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4] [5 6 7 8 9]
[0 1] [2 3] [4 5] [6 7] [8 9]


* `vsplit()`: 수직 분할, 1차원으로 분할

In [119]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2, c2 = np.vsplit(a2, [2])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[[7 8 9]]


* `hsplit()`: 수평 분할, 2차원으로 분할

In [120]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2, c2 = np.hsplit(a2, [2])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]
 [7 8]]
[[3]
 [6]
 [9]]


* `dsplit()`: 깊이 분할, 3차원으로 분할

In [121]:
a3 = np.arange(1,28).reshape(3,3,3)
print(a3)
b3, c3 = np.dsplit(a3, [2])
print(b3)
print(c3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[[ 1  2]
  [ 4  5]
  [ 7  8]]

 [[10 11]
  [13 14]
  [16 17]]

 [[19 20]
  [22 23]
  [25 26]]]
[[[ 3]
  [ 6]
  [ 9]]

 [[12]
  [15]
  [18]]

 [[21]
  [24]
  [27]]]




---



## 배열 연산

* NumPy의 배열 연산은 벡터화(vectorized) 연산을 사용
* 일반적으로 NumPy의 범용 함수(universal functions)를 통해 구현
* 배열 요소에 대한 반복적인 계산을 효율적으로 수행

### 브로드캐스팅(Broadcasting)

### 산술 연산(Arithmetic Operators)

#### 절대값 함수(Absolute Function)

* `absolute()`, `abs()`: 내장된 절대값 함수

#### 제곱/제곱근 함수

* `square`, `sqrt`: 제곱, 제곱근 함수

#### 지수와 로그 함수 (Exponential and Log Function)

#### 삼각 함수(Trigonometrical Function)


### 집계 함수(Aggregate Functions)

#### sum(): 합 계산

#### cumsum(): 누적합 계산

#### diff(): 차분 계산

#### prod(): 곱 계산

#### cumprod(): 누적곱 계산

#### dot()/matmul(): 점곱/행렬곱 계산

#### tensordot(): 텐서곱 계산

#### cross(): 벡터곱

#### inner()/outer(): 내적/외적

#### mean(): 평균 계산

#### std(): 표준 편차 계산

#### var(): 분산 계산

#### min(): 최소값

#### max(): 최대값

#### argmin(): 최소값 인덱스

#### argmax(): 최대값 인덱스

#### median(): 중앙값

#### percentile(): 백분위 수



#### any()

#### all()

### 비교 연산(Comparison Operators)


#### 불리언 연산자(Boolean Operators)


### 배열 정렬

#### 부분 정렬

* `partition()`: 배열에서 k개의 작은 값을 반환

## 배열 입출력


sample_data




---

